### ISSUE TITLE
Error on MV / live on newer version

### ISSUE THREAD

**Issue by 11-59pm** [chinosk6/scsp-localify#41]
![image](https://github.com/user-attachments/assets/d1d94f12-a703-4755-94c6-c9bb7a54f2b4)

When viewing MV or playing live on DMM version, the game crashes.

Seems to be an issue related with new version.

**Comment by chinosk6** [comment]
fixed: [Actions](../actions/runs/11826008556)

**Comment by chinnen0308** [comment]
Thanks for the correction.
But still crashes when using free camera while watching MV.
What could be the cause?
